// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Image {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    order: number;
    image: { data: Media };
    cloudinaryPublicId?: string;
  };
}
export interface Image_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  order: number;
  image: Media_Plain;
  cloudinaryPublicId?: string;
}

export interface Image_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  order: number;
  image: number;
  cloudinaryPublicId?: string;
}

export interface Image_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  order: number;
  image: AdminPanelRelationPropertyModification<Media_Plain>;
  cloudinaryPublicId?: string;
}
