// Interface automatically generated by schemas-to-ts

import { Collection } from '../../../collection/content-types/collection/collection';
import { Image } from '../../../image/content-types/image/image';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Collection_Plain } from '../../../collection/content-types/collection/collection';
import { Image_Plain } from '../../../image/content-types/image/image';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Painting {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description?: string;
    technique?: string;
    measures?: string;
    collection?: { data: Collection };
    imagess: { data: Image[] };
    images: { data: Media[] };
  };
}
export interface Painting_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  technique?: string;
  measures?: string;
  collection?: Collection_Plain;
  imagess: Image_Plain[];
  images: Media_Plain[];
}

export interface Painting_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  technique?: string;
  measures?: string;
  collection?: number;
  imagess: number[];
  images: number[];
}

export interface Painting_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  technique?: string;
  measures?: string;
  collection?: AdminPanelRelationPropertyModification<Collection_Plain>;
  imagess: AdminPanelRelationPropertyModification<Image_Plain>;
  images: AdminPanelRelationPropertyModification<Media_Plain>[];
}
