name: Keep Strapi Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping /ping
        id: test_ping
        run: |
          set -e
          # Cambia qui con il tuo dominio Render
          URL="https://TUO-SERVIZIO.onrender.com"
          for path in "" "api"; do
            echo "→ Testing $URL/${path:+$path/}ping"
            # -v per debug, -m 10 timeout, -w per solo status
            HTTP_STATUS=$(curl -v -m 10 -s -w "%{http_code}" "$URL/${path:+$path/}ping" -o response.txt || true)
            echo "Status for /${path:+$path/}ping: $HTTP_STATUS"
            if [ "$HTTP_STATUS" -eq 200 ]; then
              echo "✅ Success on /${path:+$path/}ping"
              exit 0
            fi
            echo "--- response body ---"
            cat response.txt || true
            echo "----------------------"
          done

          echo "::error::All ping attempts failed"
          exit 1

      - name: Complete
        if: success()
        run: echo "🎉 Strapi is alive!"